# Generated by Django 2.0.7 on 2018-07-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180718_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
